# Generated by Django 2.1.7 on 2020-02-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WasteManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compType', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='complainimage')),
                ('dated', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteManagement.Public')),
            ],
        ),
    ]
